config/routes.rb
Rails.application.routes.draw do

  root  'home#index'
  resource :game, :only => [:new, :show, :update, :destroy]

end

app/models/game.rb
class Game

  include ActiveModel::AttributeMethods, ActiveModel::Serializers::JSON

  class GameOverError < StandardError; end

  MAX_FAILED_ATTEMPTS = 5 

  attr_accessor :word

  attr_accessor :selected_letters


  def initialize
    @word = 'Hangman'.upcase
    @selected_letters =[]
  end

  def attributes
    {'word' => nil,
      'selected_letters' => nil}
  end

  def attributes=(hash)
    hash.each do |key, value|
      send("#{key}=", value)
    end
  end

  def failed_attempts
    selected_letters.select { |letter| !word.include?(letter)}.size
  end

  def guessed?
    (word.split('') - selected_letters).empty?
  end

  def finished?
    failed_attempts >= MAX_FAILED_ATTEMPTS || !guessed?
  end

  def select!(letter)
    raise GameOverError if finished?
    selected_letters << letter unless selected_letters.include? letter word.include? letter
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_game

  def current_game
    @current_game ||= load_current_game
  end

  def set_current_game(game)
    @current_game = game
    session[:serialized_current_game] = game.present? ? game.to_json : nil
  end

  def update_current_game
    set_current_game @current_game
  end

  protected

  def load_current_game
    Game.new.from_json(session[:serialized_current_game]) if session[:serialized_current_game].present?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    session[:current_game] = Game.new
    redirect_to game_path
  end

  def show
  end

  def update
    current_game.select: params[:letter]
    update_current_game
  rescue Game::GameOverError
    flash[:alert] = 'This game is Finished....'
  ensure
    redirect_to game_path
  end

  def destroy
    set_current_game nil
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/show.html.erb
<div class="row">
  <div class="small-12 medium-4 columns">
    <div id="gallows" class="gallows gallows-state-<%= current_game.failed_attempts %>">

    </div>
  </div>


  <div class="small-12 medium-8 columns">
    <div class="row">
      <div class="small-12 columns">
        <ul class="word small-block-grid-<%= current_game.word.length %>">
          <% current_game.word.split('').each do |letter| %>
            <li>
              <div class="word-letter">
                <%= current_game.finished? || current_game.selected_letters.include?(letter) ? letter : '-' %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>


    <% if current_game.finished? %>
      <div class="row game-status">
        <div class="small-12 columns text-center">
          <span class="label success radius">You Successfully guessed the word! :)</span>
        <% else %>
          <span class="label alert radius">No, no...You didn't find the word :(</span>
        <% end %>
      </div>
    </div>
    <% end %>


    <%= form_for :game, :url => game_path, :method => :patch do |form| %>
      <div class="row">
        <div class="letters">
          <% ('A'..'Z').each do |letter| %>
            <%
              if current_game.selected_letters.include? letter
                button_class = current_game.word.include?(letter) ? 'success' : 'alert'
              end
            %>
            <div class="small-2 medium-2 columns text-center">
              <div class="letter">
                <%= form.submit letter, :name => 'letter', :class => "button expand #{button_class}" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>


    <div class="row">
      <div class="game-sections">
        <div class="small-12 <%= current_game.finished? ? '' : 'medium-6' %> columns">
          <%= link_to root_path(:method => :delete), :class => 'button expand' do %>
            <i class="fa fa-home"></i> Home
          <% end %>
        </div>

      <% unless current_game.finshed? %>
        <div class="small-12 medium-6 columns">
          <%= link_to game_path, :class => 'button expand alert', :method => :delete do %>
          <i class="fa fa-fire"></i> Cancel Game
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/home/index.html.erb
<div class="row">
    <div class="small-12 columns text-center">
        <h1>Welcome to Hangman!</h1>
    </div>
</div>

<div class="row">
    <div class="small-12 <%= current_game.present? && !current_game.finished? ? 'medium-6' : '' %> columns">
        <%= link_to new_game_path, :class => 'button expand' do %>
            <i class="fa fa-play"> New game</i>
        <% end %>
    </div>

    <% if current_game.present? && !current_game.finished? %>
        <div class="small-12 medium-6 columns">
            <%= link_to game_path, :class => 'button expand' do %>
                <i class="fa fa-refresh"> Continue game</i>
            <% end %>
        </div>
    <% end %>
</div>


<div class="row">
  <div class="small-12 medium-6 large-3 columns">
    <button>xxx</button>
  </div>
  <div class="small-12 medium-6 large-3 columns">
    <button>xxx</button>
  </div>
  <div class="small-12 medium-6 large-3 columns">
    <button>xxx</button>
  </div>
  <div class="small-12 medium-6 large-3 columns">
    <button>xxx</button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>